### ISSUE TITLE
Facing issue while converting the Born effective charges from Quantum Espresso to Phonopy format.

### ISSUE THREAD

**Issue by shivamjani** [phonopy/phonopy#153]
Hi Togo,

Facing a similar issue in qe.py praser. Unable to use any functionality of QE with phonopy.

python make_born_q2r.py scf.in Ca3Sb2.fc > BORN

Traceback (most recent call last):
File "/home/smj/Systems/Ca3Sb2/New/**make_born_q2r.py", line 10, in
cell, _ = read_pwscf(primcell_filename)**
File "/home/smj/anaconda3/envs/phonopy/lib/**python3.9/site-packages/phonopy/interface/qe.py**", line 83, in read_pwscf
pwscf_in = PwscfIn(f.readlines())
File "/home/smj/anaconda3/envs/phonopy/lib/**python3.9/site-packages/phonopy/interface/qe.py**", line 211, in init
self._collect(lines)
File "/home/smj/anaconda3/envs/phonopy/lib/**python3.9/site-packages/phonopy/interface/qe.py**", line 254, in _collect
getattr(self, self._set_methods[tag_name])()
File "/home/smj/anaconda3/envs/**phonopy/lib/python3.9/site-packages/phonopy/interface/qe.py**", line 292, in _set_lattice
raise RuntimeError(
**RuntimeError: As a unit, alat, angstrom, and bohr can be only used.**

Followed all the instructions you mentioned in the link,
https://github.com/phonopy/phonopy/tree/master/example/NaCl-QE-q2r 

I have attached the files along,

[files.zip](https://github.com/phonopy/phonopy/files/6866568/files.zip)

**Comment by atztogo** [comment]
You use unsupported tags in scf.in.
See https://phonopy.github.io/phonopy/qe.html#supported-qe-pw-tags.

**Comment by atztogo** [comment]
I close this issue because no reply for a while.
