### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by rashigeek** [phonopy/phonopy#197]
I am getting the following error when I try to generate a FORCE_CONSTANTS file from a vasprun.xml file. Here is the output of the program: 
Python version 3.9.7
Spglib version 1.16.3

Traceback (most recent call last):
  File "/Users/ahmedelrashidy/opt/anaconda3/bin/phonopy", line 45, in <module>
    main(**argparse_control)
  File "/Users/ahmedelrashidy/opt/anaconda3/lib/python3.9/site-packages/phonopy/cui/phonopy_script.py", line 1691, in main
    is_error = create_FORCE_CONSTANTS(filename, write_hdf5, log_level)
  File "/Users/ahmedelrashidy/opt/anaconda3/lib/python3.9/site-packages/phonopy/interface/vasp.py", line 150, in create_FORCE_CONSTANTS
    force_constants, atom_types = parse_force_constants(filename)
  File "/Users/ahmedelrashidy/opt/anaconda3/lib/python3.9/site-packages/phonopy/interface/vasp.py", line 193, in parse_force_constants
    return vasprun.read_force_constants()
  File "/Users/ahmedelrashidy/opt/anaconda3/lib/python3.9/site-packages/phonopy/interface/vasp.py", line 544, in read_force_constants
    return self._get_force_constants(vasprun)
  File "/Users/ahmedelrashidy/opt/anaconda3/lib/python3.9/site-packages/phonopy/interface/vasp.py", line 579, in _get_force_constants
    version_nums = [int(v) for v in version_str.split(".")]
  File "/Users/ahmedelrashidy/opt/anaconda3/lib/python3.9/site-packages/phonopy/interface/vasp.py", line 579, in <listcomp>
    version_nums = [int(v) for v in version_str.split(".")]
ValueError: invalid literal for int() with base 10: '18Apr17-6-g9f103f2a35'

I am not sure where the string  '18Apr17-6-g9f103f2a35' is getting passed in from. But I think that is where the issue is. I used phonopy to generate FORCE_SETS files before and it works like a charm. I am not sure why generating a FORCE_CONSTANTS is giving me this error.

I am running the code on a Mac pro 2019 with an i7 processor in a conda environment

**Comment by atztogo** [comment]
This is fixed at https://github.com/phonopy/phonopy/pull/193.
