### ISSUE TITLE
workin with --pa flag

### ISSUE THREAD

**Issue by lorcat** [phonopy/phonopy#307]
Dear Colleagues,
I am trying to calculate phonon spectra using phonopy + QE. My structure is body centered.

When I try to do:
phonopy --qe -c ./[structure.in](http://structure.in/) -d --dim 2 2 2 --pa I

I get the following error message. Is there a way to fix it? 

If I skip the --pa flag - the structure is considered to be primitive.
In principle, the total number of atoms makes sense, still it would be nice to understand the work under the hood.

Thank you!

        _
  _ __ | |__   ___  _ __   ___   _ __  _   _
 | '_ \| '_ \ / _ \| '_ \ / _ \ | '_ \| | | |
 | |_) | | | | (_) | | | | (_) || |_) | |_| |
 | .__/|_| |_|\___/|_| |_|\___(_) .__/ \__, |
 |_|                            |_|    |___/
                                      2.12.0

Python version 3.6.8
Spglib version 2.0.2

Traceback (most recent call last):
  File "/home/glazyrin/.local/bin//phonopy", line 45, in <module>
    main(**argparse_control)
  File "/home/glazyrin/.local/lib/python3.6/site-packages/phonopy/cui/phonopy_script.py", line 1722, in main
    phonon = init_phonopy(settings, cell_info, symprec, log_level)
  File "/home/glazyrin/.local/lib/python3.6/site-packages/phonopy/cui/phonopy_script.py", line 1606, in init_phonopy
    log_level=log_level,
  File "/home/glazyrin/.local/lib/python3.6/site-packages/phonopy/api_phonopy.py", line 175, in __init__
    self._build_primitive_cell()
  File "/home/glazyrin/.local/lib/python3.6/site-packages/phonopy/api_phonopy.py", line 3528, in _build_primitive_cell
    store_dense_svecs=self._store_dense_svecs,
  File "/home/glazyrin/.local/lib/python3.6/site-packages/phonopy/structure/cells.py", line 66, in get_primitive
    positions_to_reorder=positions_to_reorder,
  File "/home/glazyrin/.local/lib/python3.6/site-packages/phonopy/structure/cells.py", line 463, in __init__
    self._run(supercell, positions_to_reorder=positions_to_reorder)
  File "/home/glazyrin/.local/lib/python3.6/site-packages/phonopy/structure/cells.py", line 601, in _run
    supercell, positions_to_reorder=positions_to_reorder
  File "/home/glazyrin/.local/lib/python3.6/site-packages/phonopy/structure/cells.py", line 616, in _create_primitive_cell
    positions_to_reorder=positions_to_reorder,
  File "/home/glazyrin/.local/lib/python3.6/site-packages/phonopy/structure/cells.py", line 890, in _trim_cell
    relative_axes, cell, symprec=symprec, positions_to_reorder=positions_to_reorder
  File "/home/glazyrin/.local/lib/python3.6/site-packages/phonopy/structure/cells.py", line 733, in __init__
    self._run(cell, relative_axes, positions_to_reorder, symprec)
  File "/home/glazyrin/.local/lib/python3.6/site-packages/phonopy/structure/cells.py", line 810, in _run
    raise RuntimeError("Remapping of atoms by TrimmedCell failed.")
RuntimeError: Remapping of atoms by TrimmedCell failed.

**Comment by atztogo** [comment]
This is an old issue, so will be closed. If you haven't solved this, please reopen this issue.
