### ISSUE TITLE
DEPRECATION: spglib has removed ASE Atoms-like input.

### ISSUE THREAD

**Issue by bfield1** [phonopy/phonopy#331]
Phonopy claims to support `spglib` version 2.0 and higher (https://github.com/phonopy/phonopy/blob/develop/requirements.txt). To interface with spglib, Phonopy uses an ASE Atoms-like form (in this case, a child of `PhonopyAtoms`) which is passed into spglib, such as in the following code (where `phonon` is a `Phonopy` instance):

https://github.com/phonopy/phonopy/blob/e913bbe07395d75b821c68f920ea57e6395adf9b/phonopy/cui/show_symmetry.py#L61-L63

However, using ASE Atoms-like input for spglib is [deprecated](https://github.com/spglib/spglib/blob/3a4ba41f4ce1cf4e76d37fe6535dd0bf76b24b42/python/spglib/spglib.py#L1553), and is [completely absent in spglib 2.3.0](https://github.com/spglib/spglib/pull/386).

As such, when I call `phonopy --show-symmetry` with `spglib` version 2.3.0 installed, I get an error (traceback at bottom of post), because spglib no longer knows how to handle Atoms-like inputs.

The current work-around is to downgrade spglib to 2.2.0 or less. When I have spglib 2.2.0 installed, Phonopy runs fine.

A fix would involve converting the structures to [spglib cell format](https://spglib.readthedocs.io/en/stable/python-interface.html#crystal-structure-cell) before passing to spglib.

----------------------------------

```python
Traceback (most recent call last):
  File "/Users/BField/anaconda3/envs/dft/bin/phonopy", line 45, in <module>
    main(**argparse_control)
  File "/Users/BField/anaconda3/envs/dft/lib/python3.11/site-packages/phonopy/cui/phonopy_script.py", line 1836, in main
    show_symmetry_info_then_exit(cell_info, symprec)
  File "/Users/BField/anaconda3/envs/dft/lib/python3.11/site-packages/phonopy/cui/phonopy_script.py", line 1667, in show_symmetry_info_then_exit
    check_symmetry(phonon, cell_info["optional_structure_info"])
  File "/Users/BField/anaconda3/envs/dft/lib/python3.11/site-packages/phonopy/cui/show_symmetry.py", line 60, in check_symmetry
    (bravais_lattice, bravais_pos, bravais_numbers) = spglib.refine_cell(
                                                      ^^^^^^^^^^^^^^^^^^^
  File "/Users/BField/anaconda3/envs/dft/lib/python3.11/site-packages/spglib/spglib.py", line 1352, in refine_cell
    lattice, _positions, _numbers, _ = _expand_cell(cell)
                                       ^^^^^^^^^^^^^^^^^^
  File "/Users/BField/anaconda3/envs/dft/lib/python3.11/site-packages/spglib/spglib.py", line 1985, in _expand_cell
    lattice = np.array(np.transpose(cell[0]), dtype="double", order="C")
                                    ~~~~^^^
TypeError: 'Primitive' object is not subscriptable
```

**Comment by atztogo** [comment]
Thanks @bfield1 for your comprehensible bug report. Fixed #332.
