### ISSUE TITLE
Non-anlytic correction calculation issue

### ISSUE THREAD

**Issue by tingguangli** [phonopy/phonopy#420]
Hi There,

I have an issue when I use phonopy-vasp-born, the error message is below:

phonopy-vasp-born 
Traceback (most recent call last):
  File "/home/tl236/Apps/anaconda3/envs/phonopy/bin/phonopy-vasp-born", line 10, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/tl236/Apps/anaconda3/envs/phonopy/lib/python3.12/site-packages/phonopy/scripts/phonopy_vasp_born.py", line 154, in run
    borns, epsilon, atom_indices = get_born_vasprunxml(
                                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/tl236/Apps/anaconda3/envs/phonopy/lib/python3.12/site-packages/phonopy/interface/vasp.py", line 495, in get_born_vasprunxml
    return elaborate_borns_and_epsilon(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tl236/Apps/anaconda3/envs/phonopy/lib/python3.12/site-packages/phonopy/structure/symmetry.py", line 540, in elaborate_borns_and_epsilon
    assert len(borns) == len(ucell), "num_atom %d != len(borns) %d" % (
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: num_atom 64 != len(borns) 0

As you noticed that I use 64 atom supercell for VASP calculation. I saw an option --pa in the reference page to resolve the supercell issue for NAC, could you provide with more detailed command to resolve this issue? Thanks a lot!

Best Regards,
Tingguang

**Comment by atztogo** [comment]
Please send your question to the phonopy mailing list.
