### ISSUE TITLE
`numpy._core._exceptions.MemoryError` in Windows NumPy 2

### ISSUE THREAD

**Issue by DanielYang59** [phonopy/phonopy#476]
Not sure if this should be resolved by `2.33.0` or not, maybe a known issue? https://github.com/conda-forge/phonopy-feedstock/pull/158#issuecomment-2271372910

Test env:

```
Microsoft Windows [Version 10.0.26100.2454]

Python 3.10.0

phonopy==2.33.0
numpy==2.0.2
```

```python

import numpy as np

from phonopy import Phonopy
from phonopy.file_IO import parse_FORCE_CONSTANTS
from phonopy.structure.atoms import PhonopyAtoms

from pymatgen.core import Structure


def get_phonopy_structure(pmg_structure: Structure) -> PhonopyAtoms:
    """
    Convert a pymatgen Structure object to a PhonopyAtoms object.

    Args:
        pmg_structure (pymatgen Structure): A Pymatgen structure object.
    """
    symbols = [site.specie.symbol for site in pmg_structure]

    return PhonopyAtoms(
        symbols=symbols,
        cell=pmg_structure.lattice.matrix,
        scaled_positions=pmg_structure.frac_coords,
        magnetic_moments=pmg_structure.site_properties.get("magmom"),
    )

structure = Structure.from_file("POSCAR-NaCl.txt")
supercell_matrix = np.eye(3) * 2
force_constants = parse_FORCE_CONSTANTS("FORCE_CONSTANTS.txt")

structure_phonopy = get_phonopy_structure(structure)
phonon = Phonopy(structure_phonopy, supercell_matrix=supercell_matrix)
```

Test files (have to add `.txt` extension to upload):
[FORCE_CONSTANTS.txt](https://github.com/user-attachments/files/18108583/FORCE_CONSTANTS.txt)
[POSCAR-NaCl.txt](https://github.com/user-attachments/files/18108584/POSCAR-NaCl.txt)

Gives
```
Traceback (most recent call last):
  File "d:\pymatgen\debug\test.py", line 32, in <module>
    phonon = Phonopy(structure_phonopy, supercell_matrix=supercell_matrix)
  File "C:\Users\Yang\anaconda3\envs\py310\lib\site-packages\phonopy\api_phonopy.py", line 293, in __init__
    self._build_primitive_cell()
  File "C:\Users\Yang\anaconda3\envs\py310\lib\site-packages\phonopy\api_phonopy.py", line 4146, in _build_primitive_cell
    self._primitive = get_primitive(
  File "C:\Users\Yang\anaconda3\envs\py310\lib\site-packages\phonopy\structure\cells.py", line 886, in get_primitive
    return Primitive(
  File "C:\Users\Yang\anaconda3\envs\py310\lib\site-packages\phonopy\structure\cells.py", line 386, in __init__
    self._run(supercell, positions_to_reorder=positions_to_reorder)
  File "C:\Users\Yang\anaconda3\envs\py310\lib\site-packages\phonopy\structure\cells.py", line 554, in _run
    (self._smallest_vectors, self._multiplicity) = self._get_smallest_vectors(
  File "C:\Users\Yang\anaconda3\envs\py310\lib\site-packages\phonopy\structure\cells.py", line 650, in _get_smallest_vectors
    svecs, multi = get_smallest_vectors(
  File "C:\Users\Yang\anaconda3\envs\py310\lib\site-packages\phonopy\structure\cells.py", line 1098, in get_smallest_vectors
    spairs = ShortestPairs(
  File "C:\Users\Yang\anaconda3\envs\py310\lib\site-packages\phonopy\structure\cells.py", line 1165, in __init__
    svecs, multi = self._run_dense()
  File "C:\Users\Yang\anaconda3\envs\py310\lib\site-packages\phonopy\structure\cells.py", line 1239, in _run_dense
    shortest_vectors = np.zeros(
numpy._core._exceptions.MemoryError: Unable to allocate 45.7 PiB for an array with shape (2143661127108530, 3) and data type float64
```

**Comment by atztogo** [comment]
Unfortunately windows is not supprted currently. If you really want to run on windows, please try it on WSL.

**Comment by atztogo** [comment]
Thanks for your report, too. Your log contains valuable information.

**Comment by atztogo** [comment]
I don't know how to set up Windows environment for installing phonopy. Could it be possible for you try the latest develop branch?

**Comment by atztogo** [comment]
I succeeded to build phonopy On conda-forge build system, https://github.com/conda-forge/phonopy-feedstock/pull/188

**Comment by DanielYang59** [comment]
It appears to me at least the above code snippet runs without any error now :)

Installed from:
```
pip install git+https://github.com/phonopy/phonopy.git@develop
```

Versions:
```
>>> pip freeze | grep numpy
numpy==2.0.0

>>> pip freeze | grep phonopy
phonopy @ git+https://github.com/phonopy/phonopy.git@fc049a9ccce0c2692056efcfce5322b4be5cb677
```

**Comment by atztogo** [comment]
OK. Thanks @DanielYang59!

**Comment by DanielYang59** [comment]
No problem, I just tested on `pymatgen` as well, looks like current develop branch works well for NP2 on Windows: https://github.com/materialsproject/pymatgen/pull/4227

(ignore the macos failure, irrelevant to phonopy I'm sure)

**Comment by atztogo** [comment]
@DanielYang59, I released phonopy 2.33.2 including this fix.

**Comment by DanielYang59** [comment]
@atztogo Thanks for the quick fix and everything, I assume you mean version `2.33.3`, and it seems to fix Windows-related NP2 issues: https://github.com/materialsproject/pymatgen/pull/4227

**Comment by JaGeo** [comment]
@atztogo @DanielYang59 thank you so much. This helps a lot with using phonopy for teaching!

**Comment by atztogo** [comment]
>I assume you mean version 2.33.3

Yes!
